/* Tower of Echoes v0.57 — Golden Land minigames, chip economy, and exhibition combat. */
(()=>{
  const RULES=Object.freeze({entryFee:2,promoGrant:6,maxGames:3,chipGold:10,maxPurchase:5,managerFee:3,managerReward:10,managerTurns:6,managerHp:{2:120,3:160,4:200}});
  const DEALER_BASE={silhouette:'통일된 성인 여성 버니 딜러 실루엣',dressCode:'정장형 판타지 카지노 유니폼과 토끼 귀 머리장식',copyRule:'기존 캐릭터·작품을 직접 복제하지 않는 독자 디자인'};
  const DEALERS={
    dice:{id:'plum',name:'매',game:'황금 주사위',theme:'매화',color:'#c93d62',hair:'긴 적갈빛 웨이브와 낮은 올림머리',personality:'밝고 능숙한 에이스 딜러',costume:'하이웨이스트 전신 팬티스타킹 위 원피스형 바니슈트 + 가터벨트 + 허벅지 밴드',mood:'매화빛 벨벳과 황금 주사위가 놓인 품위 있는 테이블',art:'assets/golden-dealer-plum-v4.webp'},
    slots:{id:'orchid',name:'난',game:'슬롯머신',theme:'난초',color:'#d6a83c',hair:'긴 금발 웨이브',personality:'화사하고 사교적인 노련한 딜러',costume:'하이웨이스트 전신 팬티스타킹 위 원피스형 바니슈트 + 가터벨트 + 허벅지 밴드',mood:'아이보리와 금빛 난초 장식이 반짝이는 기계 테이블',art:'assets/golden-dealer-orchid-v4.webp'},
    shell:{id:'chrysanthemum',name:'국',game:'야바위',theme:'국화',color:'#8065d6',hair:'긴 보랏빛 웨이브',personality:'나른하고 퇴폐적인 딜러',costume:'하이웨이스트 전신 팬티스타킹 위 원피스형 바니슈트 + 가터벨트 + 허벅지 밴드',mood:'자수정과 금빛 국화 장식이 놓인 시각 추적 테이블',art:'assets/golden-dealer-chrysanthemum-v4.webp'},
    thief:{id:'bamboo',name:'죽',game:'도둑잡기',theme:'대나무',color:'#3b9c78',hair:'짧은 흑갈색 보브와 비취빛 포인트',personality:'차갑고 세련된 딜러',costume:'하이웨이스트 전신 망사 팬티스타킹 위 원피스형 바니슈트 + 가터벨트 + 허벅지 밴드',mood:'대나무 문양과 용의자 토큰이 놓인 추리 테이블',art:'assets/golden-dealer-bamboo-v5.webp'}
  };
  const GAMES={dice:{name:'황금 주사위',dealer:'plum',desc:'주사위 5개를 최대 3회 굴립니다. 원하는 주사위를 HOLD해 가장 높은 족보를 완성하십시오.'},slots:{name:'슬롯머신',dealer:'orchid',desc:'릴을 한 번 작동합니다. 화면에 표시된 심볼 조합과 지급 칩은 고정 확률표를 따릅니다.'},shell:{name:'야바위',dealer:'chrysanthemum',desc:'공개된 황금 구슬을 실제 컵 이동으로 추적한 뒤 마지막 위치를 선택하십시오.'},thief:{name:'도둑잡기',dealer:'bamboo',desc:'다섯 용의자 토큰과 최대 두 개의 논리 단서를 이용해 도둑을 지목하십시오.'}};
  const NPCS={exchange:{name:'니블',role:'환전상',species:'여성 고블린',design:'영리한 판타지 고블린 출납원. 큰 귀, 계산 안경, 동전 저울과 장부를 사용하는 독자 디자인.',art:'assets/golden-exchange-goblin-v2.webp'},manager:{name:'실베른',role:'카드배틀 지배인',design:'은발의 성인 여성. 슬림한 집사풍 정장과 절제된 장식, 여학교 왕자님 같은 중성적 우아함과 냉정한 태도.',art:'assets/golden-card-manager-v2.webp'}};
  const SLOT_RESULTS=[{limit:20,payout:0,symbols:['♠','♦','♣'],label:'서로 다른 문양'},{limit:40,payout:1,symbols:['●','♠','♦'],label:'황금 칩 1개'},{limit:60,payout:2,symbols:['♠','♠','♦'],label:'일반 한 쌍'},{limit:80,payout:4,symbols:['♛','♛','♣'],label:'왕관 한 쌍'},{limit:95,payout:6,symbols:['♦','♦','♦'],label:'보석 삼중주'},{limit:100,payout:12,symbols:['★','★','★'],label:'JACKPOT'}];
  const $=selector=>document.querySelector(selector),clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const hash=text=>{let h=2166136261;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const unit=(seed,label,index=0)=>{let x=(hash(`${seed}:${label}:${index}`)+0x6D2B79F5)>>>0;x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296},int=(seed,label,index,max)=>Math.floor(unit(seed,label,index)*max);
  const legacySpinKey=String.fromCharCode(114,111,117,108,101,116,116,101);
  function defaultState(seed=1){return{schemaVersion:3,seed:seed>>>0,active:false,exited:false,entryEventId:null,promoGranted:false,promoChips:0,chips:0,goldPurchased:0,plays:0,winnings:0,gamesUsed:{dice:0,slots:0,shell:0,thief:0},gameStates:{dice:null,slots:null,shell:null,thief:null},managerInvite:false,managerEvent:{unlocked:false,started:false,completed:false,result:null,snapshot:null}}}
  function seedFromRun(){return hash(`${state.map_seed||state.map?.seed||0}:${state.stage||0}:${state.hero||0}:GLD-E01`)}
  function migrate(old){
    const fresh=defaultState(Number(old?.seed)||seedFromRun());if(!old)return fresh;const oldUsed=old.gamesUsed||{},legacyUsed=Math.max(0,Math.floor(Number(oldUsed[legacySpinKey])||0));
    Object.assign(fresh,{active:Boolean(old.active),exited:Boolean(old.exited),entryEventId:old.entryEventId||null,promoGranted:Boolean(old.promoGranted),promoChips:Math.max(0,Math.floor(Number(old.promoChips)||0)),chips:Math.max(0,Math.floor(Number(old.chips)||0)),goldPurchased:clamp(Math.floor(Number(old.goldPurchased)||0),0,RULES.maxPurchase),plays:Math.max(0,Math.floor(Number(old.plays)||0)),winnings:Math.floor(Number(old.winnings)||0)});
    fresh.gamesUsed={dice:Math.max(legacyUsed,Math.floor(Number(oldUsed.dice)||0)),slots:Math.floor(Number(oldUsed.slots)||0),shell:Math.floor(Number(oldUsed.shell)||0),thief:Math.floor(Number(oldUsed.thief)||0)};
    fresh.gameStates={dice:fresh.gamesUsed.dice?{migrated:true,finalized:true,result:'이전 추첨 게임 완료',payout:0,settled:true}:null,slots:old.gameStates?.slots||null,shell:old.gameStates?.shell||null,thief:old.gameStates?.thief||null};
    fresh.managerInvite=Boolean(old.managerInvite||old.managerEvent?.unlocked);fresh.managerEvent={unlocked:fresh.managerInvite,started:Boolean(old.managerEvent?.started),completed:Boolean(old.managerEvent?.completed),result:old.managerEvent?.result||null,snapshot:old.managerEvent?.snapshot||null};return fresh;
  }
  function sanitize(s){s.gamesUsed??={};s.gameStates??={};s.managerEvent??={};s.chips=Math.max(0,Math.floor(Number(s.chips)||0));s.promoChips=Math.max(0,Math.floor(Number(s.promoChips)||0));s.goldPurchased=clamp(Math.floor(Number(s.goldPurchased)||0),0,RULES.maxPurchase);s.plays=clamp(Math.floor(Number(s.plays)||0),0,RULES.maxGames);for(const id of Object.keys(GAMES)){s.gamesUsed[id]=Math.max(0,Math.floor(Number(s.gamesUsed[id])||0));if(s.gameStates[id]===undefined)s.gameStates[id]=null}s.managerEvent.unlocked=Boolean(s.managerInvite);return s}
  function ensure(){if(!state.goldenLand||state.goldenLand.schemaVersion!==3)state.goldenLand=migrate(state.goldenLand);return sanitize(state.goldenLand)}
  function persist(){sync?.();try{if(typeof localStorage!=='undefined'&&typeof SAVE_KEY!=='undefined'&&typeof saveStateJSON==='function')localStorage.setItem(SAVE_KEY,saveStateJSON())}catch{}wallet()}
  function wallet(){const s=ensure();document.querySelectorAll('[data-gl-gold]').forEach(n=>n.textContent=state.gold);document.querySelectorAll('[data-gl-promo]').forEach(n=>n.textContent=s.promoChips);document.querySelectorAll('[data-gl-chips]').forEach(n=>n.textContent=s.chips);document.querySelectorAll('[data-gl-plays]').forEach(n=>n.textContent=`${s.plays}/${RULES.maxGames}`)}
  function status(){const s=ensure();return `<div class="golden-wallet"><span>골드 <b data-gl-gold>${state.gold}</b>G</span><span>프로모션 <b data-gl-promo>${s.promoChips}</b></span><span>황금 칩 <b data-gl-chips>${s.chips}</b></span><span>일반 게임 <b data-gl-plays>${s.plays}/${RULES.maxGames}</b></span></div>`}
  function shell(title,subtitle,content,back){const modal=$('#modal');if(!modal)return;modal.className='modal golden-land-modal';modal.innerHTML=`<header class="golden-head"><button type="button" data-gl-back aria-label="이전 화면">←</button><div><small>Golden Land</small><h2>${title}</h2><p>${subtitle}</p></div>${status()}</header>${content}`;$('#overlay')?.classList.remove('hidden');modal.querySelector('[data-gl-back]').onclick=back}
  function message(text,tone=''){const node=$('[data-gl-message]');if(node){node.textContent=text;node.dataset.tone=tone}}
  function payEntry(id){const s=ensure();if(s.plays>=RULES.maxGames||s.gamesUsed[id]||s.gameStates[id]?.paid)return false;let due=RULES.entryFee;const promo=Math.min(due,s.promoChips);s.promoChips-=promo;due-=promo;if(s.chips<due){s.promoChips+=promo;return false}s.chips-=due;s.gameStates[id]??={};s.gameStates[id].paid=true;persist();return true}
  function finishGame(id,payout,text,vip=false){const s=ensure(),g=s.gameStates[id]||{};if(g.settled)return false;g.settled=true;g.payout=payout;s.gameStates[id]=g;s.chips+=payout;s.plays++;s.gamesUsed[id]=1;s.winnings+=payout-RULES.entryFee;if(vip){s.managerInvite=true;s.managerEvent.unlocked=true}s.managerEvent.unlocked=s.managerInvite;persist();message(`${text} · ${payout?`${payout} 황금 칩 획득`:'보상 없음'}${vip?' · VIP 초대 활성화':''}`,payout?'ok':'error');return true}
  function exchange(direction,amount){const s=ensure(),chips=Math.max(0,Math.floor(Number(amount)||0));if(!chips)return false;if(direction==='buy'){if(s.goldPurchased+chips>RULES.maxPurchase||state.gold<chips*RULES.chipGold)return false;state.gold-=chips*RULES.chipGold;s.chips+=chips;s.goldPurchased+=chips}else if(direction==='sell'){if(s.chips<chips)return false;s.chips-=chips;state.gold+=chips*RULES.chipGold}else return false;persist();return true}
  function openExchange(){const s=ensure(),n=NPCS.exchange,remaining=RULES.maxPurchase-s.goldPurchased;const content=`<section class="golden-npc exchange"><img class="golden-character" src="${n.art}" alt="여성 고블린 환전상 ${n.name}"><div><span>${n.species} · ${n.role}</span><h3>${n.name}</h3><p>“한 칩에 10골드. 들어올 때도, 나갈 때도 같은 값이에요.”</p></div></section><section class="golden-actions"><button type="button" data-exchange="buy" data-amount="1" ${remaining<1||state.gold<10?'disabled':''}><strong>10G → 1칩</strong><small>추가 구매 ${remaining}/5칩 남음</small></button><button type="button" data-exchange="buy" data-amount="${remaining}" ${remaining<1||state.gold<remaining*10?'disabled':''}><strong>${remaining*10}G → ${remaining}칩</strong><small>남은 구매 한도 전부 교환</small></button><button type="button" data-exchange="sell" data-amount="1" ${s.chips<1?'disabled':''}><strong>1칩 → 10G</strong><small>일반 황금 칩만 환전</small></button><button type="button" data-exchange="sell" data-amount="${s.chips}" ${s.chips<1?'disabled':''}><strong>${s.chips}칩 → ${s.chips*10}G</strong><small>일반 황금 칩 전부 환전</small></button></section><p class="golden-message" data-gl-message>프로모션 칩은 현금화할 수 없습니다.</p>`;shell('환전소','황금 칩과 골드를 같은 환율로 교환합니다.',content,openHub);document.querySelectorAll('[data-exchange]').forEach(button=>button.onclick=()=>{const ok=exchange(button.dataset.exchange,button.dataset.amount);openExchange();message(ok?'교환이 완료되었습니다.':'교환 한도 또는 보유 재화를 확인하십시오.',ok?'ok':'error')})}
  function evaluateDice(values){const counts=[...new Set(values)].map(v=>values.filter(x=>x===v).length).sort((a,b)=>b-a),unique=[...new Set(values)].sort((a,b)=>a-b),run=n=>unique.some((v,i)=>{const slice=unique.slice(i,i+n);return slice.length===n&&slice.every((x,j)=>x===v+j)});if(counts[0]===5)return{name:'황금의 오중주',payout:12,rank:8};if(run(5))return{name:'5연속',payout:8,rank:7};if(counts[0]===4)return{name:'포카드',payout:7,rank:6};if(counts[0]===3&&counts[1]===2)return{name:'풀하우스',payout:5,rank:5};if(run(4))return{name:'4연속',payout:4,rank:4};if(counts[0]===3)return{name:'삼중',payout:3,rank:3};if(counts.filter(x=>x===2).length>=2)return{name:'두 쌍',payout:2,rank:2};if(counts[0]===2)return{name:'한 쌍',payout:1,rank:1};return{name:'없음',payout:0,rank:0}}
  const newDiceState=()=>({paid:true,rollCount:0,dice:[0,0,0,0,0],holds:[false,false,false,false,false],finalized:false,result:null,settled:false});
  function rollDice(){const s=ensure();let g=s.gameStates.dice;if(!g?.paid){if(!payEntry('dice'))return false;g=s.gameStates.dice=newDiceState()}if(g.finalized||g.rollCount>=3)return false;for(let i=0;i<5;i++)if(!g.holds[i]||!g.dice[i])g.dice[i]=1+int(s.seed,'dice',g.rollCount*5+i,6);g.rollCount++;if(g.rollCount>=3)finalizeDice();else{persist();renderDiceBoard()}return true}
  function toggleHold(index){const g=ensure().gameStates.dice;if(!g||!g.rollCount||g.finalized)return false;g.holds[index]=!g.holds[index];persist();renderDiceBoard();return true}
  function finalizeDice(){const s=ensure(),g=s.gameStates.dice;if(!g||!g.rollCount||g.finalized)return false;g.finalized=true;g.result=evaluateDice(g.dice);finishGame('dice',g.result.payout,`최종 족보: ${g.result.name}`,g.result.rank>=5);renderDiceBoard();return true}
  function renderDiceBoard(){const g=ensure().gameStates.dice,board=$('[data-gl-board]');if(!board)return;if(!g){board.innerHTML='<button type="button" class="golden-primary" data-dice-roll>첫 굴림 시작 · 2칩</button>';board.querySelector('[data-dice-roll]').onclick=()=>{rollDice();renderDiceBoard()};return}board.innerHTML=`<div class="golden-dice">${g.dice.map((value,i)=>`<button type="button" data-die="${i}" class="${g.holds[i]?'held':''}" ${!g.rollCount||g.finalized?'disabled':''}><b>${value||'?'}</b><small>${g.holds[i]?'HOLD':'선택'}</small></button>`).join('')}</div><div class="golden-board-actions"><button type="button" data-dice-roll ${g.finalized||g.rollCount>=3?'disabled':''}>${g.rollCount?'재굴림':'첫 굴림'} · ${g.rollCount}/3</button><button type="button" data-dice-final ${!g.rollCount||g.finalized?'disabled':''}>결과 확정</button></div>${g.result?`<strong class="golden-result">${g.result.name} · ${g.result.payout}칩</strong>`:''}`;board.querySelectorAll('[data-die]').forEach(button=>button.onclick=()=>toggleHold(Number(button.dataset.die)));board.querySelector('[data-dice-roll]')?.addEventListener('click',rollDice);board.querySelector('[data-dice-final]')?.addEventListener('click',finalizeDice)}
  function slotResult(seed){const roll=Math.floor(unit(seed,'slots')*100);return SLOT_RESULTS.find(row=>roll<row.limit)}
  function playSlots(){const s=ensure();if(s.gameStates.slots?.settled||!payEntry('slots'))return false;const result=slotResult(s.seed);s.gameStates.slots={paid:true,settled:false,result};finishGame('slots',result.payout,`${result.symbols.join(' ')} · ${result.label}`,result.payout>=6);renderSlotsBoard();return true}
  function renderSlotsBoard(){const g=ensure().gameStates.slots,board=$('[data-gl-board]');if(!board)return;board.innerHTML=g?.result?`<div class="slot-result">${g.result.symbols.map(x=>`<b>${x}</b>`).join('')}</div><strong class="golden-result">${g.result.label} · ${g.result.payout}칩</strong>`:'<button type="button" class="golden-primary" data-slot-spin>슬롯 작동 · 2칩</button>';board.querySelector('[data-slot-spin]')?.addEventListener('click',playSlots)}
  function shellSetup(difficulty){const s=ensure();if(s.gameStates.shell?.paid||!payEntry('shell'))return false;const start=int(s.seed,'shell-start',0,3),moves=[],count=difficulty==='fast'?8:5;let positions=[0,1,2];for(let i=0;i<count;i++){const a=int(s.seed,'shell-a',i,3),b=(a+1+int(s.seed,'shell-b',i,2))%3;moves.push([a,b]);[positions[a],positions[b]]=[positions[b],positions[a]]}s.gameStates.shell={paid:true,phase:'reveal',difficulty,start,moves,final:positions.indexOf(start),selected:null,settled:false};persist();renderShellBoard();return true}
  function beginShellShuffle(){const g=ensure().gameStates.shell;if(!g||g.phase!=='reveal')return;g.phase='select';persist();renderShellBoard(true)}
  function animateShell(board,g){board.innerHTML=`<div class="shell-track">${[0,1,2].map(i=>`<button class="shell-cup" data-cup-id="${i}" disabled>컵</button>`).join('')}</div><p class="shell-motion">컵이 실제 이동 순서대로 섞이고 있습니다…</p>`;const at=[0,1,2],cups=[...board.querySelectorAll('[data-cup-id]')],delay=g.difficulty==='fast'?95:180;let step=0;const move=()=>{if(step>=g.moves.length){renderShellBoard(false);return}const[a,b]=g.moves[step++];[at[a],at[b]]=[at[b],at[a]];for(let position=0;position<at.length;position++){const cupId=at[position],cup=cups.find(node=>Number(node.dataset.cupId)===cupId);if(cup)cup.style.transform=`translateX(${(position-cupId)*110}%)`}setTimeout(move,delay)};setTimeout(move,delay)}
  function renderShellBoard(animate=false){const g=ensure().gameStates.shell,board=$('[data-gl-board]');if(!board)return;if(!g){board.innerHTML='<div class="golden-board-actions"><button type="button" data-shell-start="normal">일반 속도 · 2칩</button><button type="button" data-shell-start="fast">고속 난이도 · 2칩</button></div>';board.querySelectorAll('[data-shell-start]').forEach(button=>button.onclick=()=>shellSetup(button.dataset.shellStart));return}if(g.phase==='reveal'){board.innerHTML=`<div class="shell-track">${[0,1,2].map(i=>`<button class="shell-cup" disabled>컵 ${i+1}${i===g.start?'<i>●</i>':''}</button>`).join('')}</div><button type="button" data-shell-shuffle>구슬을 확인하고 섞기 시작</button>`;board.querySelector('[data-shell-shuffle]').onclick=beginShellShuffle;return}if(animate){animateShell(board,g);return}board.innerHTML=`<div class="shell-track">${[0,1,2].map(i=>`<button class="shell-cup" data-shell-pick="${i}" ${g.settled?'disabled':''}>컵 ${i+1}${g.settled&&i===g.final?'<i>●</i>':''}</button>`).join('')}</div>`;board.querySelectorAll('[data-shell-pick]').forEach(button=>button.onclick=()=>pickShell(Number(button.dataset.shellPick)))}
  function pickShell(index){const s=ensure(),g=s.gameStates.shell;if(!g||g.settled)return false;g.selected=index;const hit=index===g.final;finishGame('shell',hit?5:0,hit?'황금 구슬을 추적했습니다.':`황금 구슬은 컵 ${g.final+1}에 있습니다.`,hit&&g.difficulty==='fast');renderShellBoard();return hit}
  function thiefSetup(){const s=ensure();if(s.gameStates.thief?.paid||!payEntry('thief'))return false;const thief=int(s.seed,'thief',0,5),parity=thief%2,candidates=[0,1,2,3,4].filter(i=>i%2===parity),other=candidates.find(i=>i!==thief),outside=[0,1,2,3,4].find(i=>i!==thief&&i!==other);s.gameStates.thief={paid:true,thief,clues:[`도둑은 ${parity?'짝수':'홀수'} 번호 토큰에 숨어 있습니다.`,`도둑은 ${[thief,other,outside].sort((a,b)=>a-b).map(i=>i+1).join('·')}번 중 하나입니다.`],cluesViewed:0,selected:null,settled:false};persist();renderThiefBoard();return true}
  function revealClue(){const g=ensure().gameStates.thief;if(!g||g.settled||g.cluesViewed>=2)return false;g.cluesViewed++;persist();renderThiefBoard();return true}
  function renderThiefBoard(){const g=ensure().gameStates.thief,board=$('[data-gl-board]');if(!board)return;if(!g){board.innerHTML='<button type="button" class="golden-primary" data-thief-start>추리 시작 · 2칩</button>';board.querySelector('[data-thief-start]').onclick=thiefSetup;return}board.innerHTML=`<div class="thief-clues">${g.clues.slice(0,g.cluesViewed).map((clue,i)=>`<p><b>단서 ${i+1}</b> ${clue}</p>`).join('')||'<p>단서를 확인하거나 바로 용의자를 지목할 수 있습니다.</p>'}</div><div class="suspect-tokens">${[0,1,2,3,4].map(i=>`<button type="button" data-suspect="${i}" ${g.settled?'disabled':''}>${i+1}</button>`).join('')}</div><button type="button" data-clue ${g.cluesViewed>=2||g.settled?'disabled':''}>단서 확인 · ${g.cluesViewed}/2</button>${g.settled?`<strong class="golden-result">도둑은 ${g.thief+1}번</strong>`:''}`;board.querySelector('[data-clue]')?.addEventListener('click',revealClue);board.querySelectorAll('[data-suspect]').forEach(button=>button.onclick=()=>pickThief(Number(button.dataset.suspect)))}
  function pickThief(index){const s=ensure(),g=s.gameStates.thief;if(!g||g.settled)return false;g.selected=index;const hit=index===g.thief,vip=hit&&g.cluesViewed===1;finishGame('thief',hit?5:0,hit?'도둑을 찾아냈습니다.':`도둑은 ${g.thief+1}번입니다.`,vip);renderThiefBoard();return hit}
  function gameBoard(id){if(id==='dice')renderDiceBoard();else if(id==='slots')renderSlotsBoard();else if(id==='shell')renderShellBoard();else renderThiefBoard()}
  function openGame(id){const s=ensure(),spec=GAMES[id],dealer=Object.values(DEALERS).find(item=>item.id===spec.dealer),used=Boolean(s.gamesUsed[id]),limit=s.plays>=RULES.maxGames;const content=`<section class="golden-dealer" style="--dealer:${dealer.color}"><img class="golden-character" src="${dealer.art}" alt="${dealer.theme} 바니 딜러 ${dealer.name}"><div><span>${dealer.theme}의 바니 딜러</span><h3>${dealer.name}</h3><p>${dealer.hair} · ${dealer.personality}</p><small>${dealer.mood}</small></div></section><section class="golden-game"><p>${spec.desc}</p><div class="golden-game-board" data-gl-board></div><p class="golden-message" data-gl-message>${used?'이번 방문에서 이미 이용했습니다.':limit?'일반 게임 3회를 모두 이용했습니다.':'참가비 2칩 · 프로모션 칩 우선 사용'}</p></section>`;shell(spec.name,`${dealer.name}가 담당하는 일반 미니게임입니다.`,content,openHub);if(!used&&!limit)gameBoard(id)}
  function cloneRun(){const copy=typeof loadStateJSON==='function'&&typeof saveStateJSON==='function'?loadStateJSON(saveStateJSON()):JSON.parse(JSON.stringify(state));delete copy.goldenLand;delete copy.goldenExhibition;return copy}
  function restoreRun(snapshot,golden){for(const key of Object.keys(state))delete state[key];Object.assign(state,snapshot);state.goldenLand=golden;delete state.goldenExhibition}
  const exhibitionActive=()=>state.encounterKind==='golden-manager'&&Boolean(state.goldenLand?.managerEvent?.started)&&!state.goldenLand?.managerEvent?.completed;
  function startManagerBattle(){const s=ensure(),event=s.managerEvent;if(!s.managerInvite||event.started||event.completed||s.chips<RULES.managerFee)return false;s.chips-=RULES.managerFee;event.started=true;event.snapshot=cloneRun();event.floor=state.stage+1;event.turnLimit=RULES.managerTurns;state.goldenExhibition=true;state.encounterKind='golden-manager';document.body?.classList.add('golden-exhibition');persist();startBattle('golden-manager');state.hp=state.maxHp;const hp=RULES.managerHp[event.floor]||RULES.managerHp[4],enemy={id:`GL-MANAGER-${s.seed}`,name:'황금향 지배인 실베른',type:'인간형',kind:'golden-manager',rank:'BOSS',maxHp:hp,hp,attack:6+event.floor*2,block:0,slot:0,goldenManager:true};state.encounterKind='golden-manager';state.mandatoryEventBattle=true;state.enemies=[enemy];state.enemy=enemy;state.targetId=enemy.id;renderBattle();persist();return true}
  function finishManager(won,reason){const current=ensure(),event=current.managerEvent;if(!event.started||event.completed)return false;const snapshot=event.snapshot;if(!snapshot)return false;const finishTurn=state.turn||RULES.managerTurns;restoreRun(snapshot,current);event.started=false;event.completed=true;event.result={won:Boolean(won),reason,turn:finishTurn};event.snapshot=null;if(won)current.chips+=RULES.managerReward;stopStageBgm?.();document.body?.classList.remove('in-battle','golden-exhibition');$('#battleScreen')?.classList.add('hidden');$('#overlay')?.classList.remove('hidden');persist();openHub(won?'지배인 카드배틀 승리 · 10 황금 칩 획득':`지배인 카드배틀 종료 · ${reason}`);return true}
  function openManager(){const s=ensure(),event=s.managerEvent;if(!s.managerInvite||event.completed){openHub(event.completed?'이번 방문의 카드배틀은 이미 종료되었습니다.':'VIP 조건을 달성해야 관리자실이 열립니다.');return}const n=NPCS.manager,content=`<section class="golden-npc manager"><img class="golden-character" src="${n.art}" alt="카드배틀 지배인 ${n.name}"><div><span>${n.role}</span><h3>${n.name}</h3><p>“여섯 턴이면 충분하겠지요. 당신의 덱을 보여 주세요.”</p></div></section><section class="manager-event"><p>현재 덱과 유물로 지배인에게 도전합니다. 임시 HP는 최대치가 되며 전투 후 실제 상태가 복원됩니다.</p><ul><li>입장료: 일반 황금 칩 3개</li><li>제한: 6턴 · 포션/아르카나 사용 불가</li><li>지배인 HP: ${RULES.managerHp[state.stage+1]||RULES.managerHp[4]}</li><li>승리 보상: 10 황금 칩</li></ul><button type="button" class="golden-primary" data-card-battle ${s.chips<RULES.managerFee||event.started?'disabled':''}>특별 카드배틀 시작</button><p class="golden-message" data-gl-message>${s.chips<RULES.managerFee?'일반 황금 칩이 3개 필요합니다.':'방문당 한 번만 도전할 수 있습니다.'}</p></section>`;shell('관리자실','VIP 초대를 받은 등반자만 참가할 수 있습니다.',content,openHub);$('[data-card-battle]')?.addEventListener('click',startManagerBattle)}
  function openHub(notice=''){const s=ensure(),managerReady=s.managerInvite&&!s.managerEvent.completed;const content=`<section class="golden-layout"><button type="button" class="golden-room exchange" data-gl-room="exchange"><span>환전소</span><strong>${NPCS.exchange.name}</strong><small>1칩 ↔ 10골드</small></button>${Object.entries(GAMES).map(([id,g])=>{const d=Object.values(DEALERS).find(x=>x.id===g.dealer),used=s.gamesUsed[id],disabled=used||s.plays>=RULES.maxGames;return `<button type="button" class="golden-room table ${used?'used':''}" data-gl-room="${id}" style="--dealer:${d.color}" ${disabled?'disabled':''}><span>${d.theme}</span><strong>${g.name}</strong><small>${used?'이용 완료':`${d.name}의 테이블`}</small></button>`}).join('')}<button type="button" class="golden-room manager ${managerReady?'unlocked':'locked'}" data-gl-room="manager" ${managerReady?'':'disabled'}><span>관리자실</span><strong>카드배틀</strong><small>${s.managerEvent.completed?'도전 완료':managerReady?'VIP 초대 활성화':'VIP 조건 필요'}</small></button></section><p class="golden-message" data-gl-message>${notice||`일반 게임은 서로 다른 3종만 이용할 수 있습니다. 남은 프로모션 칩 ${s.promoChips}개`}</p><footer class="golden-footer"><button type="button" data-gl-leave>황금향 떠나기</button></footer>`;shell('황금향','환전소와 네 개의 미니게임 테이블이 황금빛 홀을 둘러싸고 있습니다.',content,()=>leave());document.querySelectorAll('[data-gl-room]').forEach(button=>button.onclick=()=>{const room=button.dataset.glRoom;if(room==='exchange')openExchange();else if(room==='manager')openManager();else openGame(room)});$('[data-gl-leave]')?.addEventListener('click',leave)}
  let exitHandler=null;
  function enter(options={}){if(options.source!=='event'||options.eventId!=='GLD-E01'||state.stage<1||state.stage>3)return false;const s=ensure();if(s.exited)return false;s.active=true;s.entryEventId=options.eventId;if(!s.promoGranted){s.promoGranted=true;s.promoChips=RULES.promoGrant}exitHandler=typeof options.onExit==='function'?options.onExit:null;persist();openHub('방문 프로모션 칩 6개가 지급되었습니다.');return true}
  function leave(){const s=ensure();if(exhibitionActive())return false;const refund=s.chips*RULES.chipGold;state.gold+=refund;s.chips=0;s.promoChips=0;s.active=false;s.exited=true;persist();$('#overlay')?.classList.add('hidden');const done=exitHandler;exitHandler=null;(done||window.finishMapRoom)?.();return true}
  function optimalDice(seed){const g=newDiceState();for(let roll=0;roll<3;roll++){for(let i=0;i<5;i++)if(!g.holds[i]||!g.dice[i])g.dice[i]=1+int(seed,'dice',roll*5+i,6);g.rollCount++;if(roll<2){const counts=new Map();g.dice.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const best=[...counts.entries()].sort((a,b)=>b[1]-a[1]||b[0]-a[0])[0][0],unique=[...counts.keys()].sort((a,b)=>a-b);g.holds=unique.length>=4?g.dice.map(v=>unique.includes(v)):g.dice.map(v=>v===best)}}return evaluateDice(g.dice)}
  function simulateVisit(seed,options={}){const rotation=Math.floor(unit(seed,'games')*4),ids=['dice','slots','shell','thief'],chosen=[ids[rotation],ids[(rotation+1)%4],ids[(rotation+2)%4]],results={};let chips=0,invite=false;for(const id of chosen){if(id==='dice'){const r=optimalDice(seed);results[id]=r.payout;chips+=r.payout;invite||=r.rank>=5}else if(id==='slots'){const r=slotResult(seed);results[id]=r.payout;chips+=r.payout;invite||=r.payout>=6}else if(id==='shell'){const fast=unit(seed,'shell-difficulty')<.18,success=unit(seed,'shell-skill')<(fast?.62:.72);results[id]=success?5:0;chips+=results[id];invite||=fast&&success}else{const early=unit(seed,'thief-early')<.15,success=unit(seed,'thief-solve')<(early?.4:.62);results[id]=success?5:0;chips+=results[id];invite||=early&&success}}const challenge=invite&&chips>=RULES.managerFee&&unit(seed,'manager-challenge')<(options.challengeRate??.78);let managerWon=false;if(challenge){chips-=RULES.managerFee;managerWon=unit(seed,'manager-win')<(options.managerWinRate??.52);if(managerWon)chips+=RULES.managerReward}return{chosen,results,invite,challenge,managerWon,netGold:chips*RULES.chipGold,chips}}
  const priorEnemyImage=window.enemyImage;if(priorEnemyImage)window.enemyImage=function(enemy){return enemy?.goldenManager?NPCS.manager.art:priorEnemyImage(enemy)};
  const priorPotion=window.useBagPotion;if(priorPotion)window.useBagPotion=function(...args){if(exhibitionActive())return false;return priorPotion.apply(this,args)};
  const priorDragonHeart=window.triggerDragonHeart;if(priorDragonHeart)window.triggerDragonHeart=function(...args){if(exhibitionActive())return false;return priorDragonHeart.apply(this,args)};
  if(window.TOE_ARCANA)for(const name of ['addGauge','beginBattle','beginTurn','onNormalCardPlayed','onEnemyDefeated','onBossPhase']){const prior=window.TOE_ARCANA[name];if(typeof prior==='function')window.TOE_ARCANA[name]=function(...args){if(exhibitionActive())return name.startsWith('begin')?undefined:0;return prior.apply(this,args)}}
  const priorWin=window.winBattle;if(priorWin)window.winBattle=function(...args){if(exhibitionActive())return finishManager(true,'6턴 이내 격파');return priorWin.apply(this,args)};
  const priorGameOver=window.gameOver;if(priorGameOver)window.gameOver=function(...args){if(exhibitionActive())return finishManager(false,'전투 패배');return priorGameOver.apply(this,args)};
  const priorEnd=window.endTurn;if(priorEnd)window.endTurn=function(...args){const active=exhibitionActive(),before=state.turn,result=priorEnd.apply(this,args);if(active&&exhibitionActive()&&state.turn>RULES.managerTurns&&state.turn!==before)finishManager(false,'6턴 제한 초과');return result};
  const priorLoad=window.loadGame;if(priorLoad)window.loadGame=function(...args){const result=priorLoad.apply(this,args);ensure();return result};
  window.TOE_GOLDEN_LAND={enter,leave,openHub,openExchange,openGame,openManager,startManagerBattle,finishManager,ensure,exchange,payEntry,evaluateDice,rollDice,toggleHold,finalizeDice,playSlots,shellSetup,pickShell,thiefSetup,revealClue,pickThief,simulateVisit,dealerBase:DEALER_BASE,dealers:DEALERS,games:GAMES,npcs:NPCS,rules:RULES,slotResults:SLOT_RESULTS};
})();
