const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),core=require('../card-runtime-core.js'),database=JSON.parse(fs.readFileSync(path.join(root,'data/character-cards.json')));
const context={window:{TOE_CARD_CORE:core,CHARACTER_CARD_DATABASE:database},state:{hero:6,turn:1,mana:3,innerQi:3,block:0,inventory:[],activeEnhancements:[],deck:[],hand:[],draw:[],discard:[],exhaust:[],enemies:[{id:'enemy',hp:100000,statuses:{}}],cardRuntimeErrors:[]},HEROES:Array.from({length:7},()=>({name:'이레',resourceMax:3,secondaryMax:3})),CARD_ART_ATTACK:'attack',CARD_ART_DEFENSE:'guard',specialCardArt(){return 'special'},starter(){},upgradeChosenCard(){},startBattle(){context.state.turn=1},endTurn(){context.state.turn++;context.state.mana=3},loadGame(){},hasCardProperty(c,k){return c.properties?.some(p=>p.keyword===k)},currentTarget(){return context.state.enemies[0]},aliveEnemies(){return context.state.enemies.filter(e=>e.hp>0)},dealToEnemy(e,d){e.hp-=d;return d},renderBattle(){},spawnCombatFx(){},winBattle(){throw Error('unexpected victory')},toeRandom(){return .5},console};
context.drawCards=n=>{while(n--){if(!context.state.draw.length){context.state.draw=context.state.discard;context.state.discard=[]}if(!context.state.draw.length)break;context.state.hand.push(context.state.draw.pop())}};
vm.runInNewContext(fs.readFileSync(path.join(root,'card-runtime.js'),'utf8'),context);
const api=context.window.TOE_CARD_RUNTIME,state=context.state;
function reset(hero=6){Object.assign(state,{hero,turn:1,mana:3,innerQi:3,block:0,inventory:[],activeEnhancements:[],deck:[],hand:[],draw:[],discard:[],exhaust:[],potionAmplify:false,potionBlockMultiplier:1,dragonWingFree:false,potionNextCardFree:false,cardRuntimeErrors:[]});state.enemies[0].hp=100000}
const ire=()=>api.make(api.definitions.get('ire-23'));
for(const upgraded of [false,true])for(const keywords of [[],['안식'],['안식','신속']]){
 reset();state.deck=[ire(),ire()];for(const c of state.deck){c.properties=keywords.map(keyword=>({keyword}));if(upgraded)core.applyCanonicalUpgrade(c,api.definitions.get('ire-23'))}state.hand=[state.deck[0]];state.draw=[state.deck[1]];
 for(let i=0;i<1000;i++){const c=state.hand.find(c=>c.cardId==='ire-23');if(c)context.useCard(c.id)}
 assert.equal(state.mana,3,'refund/draw cycle must stop after two instances');assert.ok(state.deck.every(c=>c.resourceCycleTurn===1));
 const before=JSON.stringify(state);for(let i=0;i<100;i++){const c=state.hand[0];if(c)context.useCard(c.id)}assert.equal(JSON.stringify(state),before,'rejected repeats must not consume/refund/draw');
 context.state=JSON.parse(JSON.stringify(state));api.hydrateState();const saved=context.state;assert.ok(saved.deck.every(c=>core.isResourceCycleLocked(c,saved)),'save/load cannot unlock same-turn reuse');context.state=state;
 context.endTurn();state.hand=[...state.deck];state.draw=[];state.discard=[];for(const c of [...state.hand])context.useCard(c.id);assert.ok(state.deck.every(c=>c.resourceCycleTurn===2));assert.equal(state.mana,keywords.includes('신속')?5:3);
 context.startBattle('normal');assert.ok(state.deck.every(c=>!core.isResourceCycleLocked(c,state)),'new battle resets per-instance guard');
}
reset();const attack=api.make(database.cards.find(c=>c.hero==='벨'&&c.startingDeck&&c.type==='공격'));attack.properties=[{keyword:'안식'},{keyword:'신속'}];attack.swiftPlays=1;state.hero=0;state.hand=[attack];const beforeMana=state.mana;context.useCard(attack.id);assert.equal(beforeMana-state.mana,Math.max(0,attack.actionCost-1));assert.equal(state.draw[0],attack,'ordinary Rest keeps its draw-pile rule');assert.equal(attack.swiftPlays,2);
const blockCard=(effects=[{op:'gainBlock',amount:10}])=>api.make({...database.cards.find(c=>c.type==='스킬'),id:'qa-block',effects,cost:{action:1,inner:0}});
for(const [bonus,mult,amp,expected] of [[0,1,false,10],[3,1,false,13],[0,2,false,20],[0,1,true,15],[3,2,true,33]]){reset(0);const c=blockCard();state.hand=[c];state.inventory=bonus?[{effect:'skillBlock',amount:bonus}]:[];state.potionBlockMultiplier=mult;state.potionAmplify=amp;context.useCard(c.id);assert.equal(state.block,expected);assert.equal(state.potionAmplify,false)}
reset(0);state.enemies[0].statuses={'출혈':1};state.inventory=[{effect:'skillBlock',amount:3}];state.potionBlockMultiplier=2;state.potionAmplify=true;const double=blockCard([{op:'gainBlock',amount:10},{op:'conditionalBlock',condition:'대상의 출혈 보유',amount:10}]);state.hand=[double];context.useCard(double.id);assert.equal(state.block,63,'each block effect modified once, skill relic once per card');
reset(0);state.inventory=[{effect:'skillBlock',amount:3}];state.potionBlockMultiplier=2;const mixed=api.make({...database.cards.find(c=>c.type==='공격'),effects:[{op:'damage',amount:10},{op:'gainBlock',amount:10}]});state.hand=[mixed];context.useCard(mixed.id);assert.equal(state.block,20);assert.equal(state.enemies[0].hp,99988,'block potion must not multiply attack damage');
for(const [delta,swift,expected] of [[-1,0,0],[1,0,2],[-1,1,0],[1,1,1]]){const c={cost:1,actionCost:1,innerCost:0,type:'스킬',domainCostDelta:delta,properties:[{keyword:'신속'}],swiftPlays:swift};assert.equal(core.paymentCost(c,{hero:0}).actionCost,expected);assert.equal(c.cost,1);assert.equal(c.actionCost,1)}
assert.equal(core.paymentCost({cost:0,actionCost:1,domainBaseCost:1,domainRole:'accelerated'},{hero:0}).actionCost,0,'legacy clock save migration');
console.log('execution modifiers regression: Ire base/upgraded 1000 attempts + reload/turn/new battle; normal Swift/Rest; block 10/13/20/15/33 + conditional/mixed; clock cost PASS');
